"""Initial migration

Revision ID: 2fb47297112d
Revises: 
Create Date: 2026-01-26 16:28:29.485972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fb47297112d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city', 'country', 'region')
    )
    op.create_index('idx_locations_city', 'locations', ['city'], unique=False)
    op.create_index('idx_locations_country', 'locations', ['country'], unique=False)
    op.create_index('idx_locations_remote', 'locations', ['remote'], unique=False)
    op.create_table('scrape_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('typical_years_min', sa.Integer(), nullable=True),
    sa.Column('typical_years_max', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_index('idx_skills_canonical_name', 'skills', ['canonical_name'], unique=False)
    op.create_index('idx_skills_category', 'skills', ['category'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('careers_url', sa.String(length=500), nullable=True),
    sa.Column('headquarters_location_id', sa.Integer(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['headquarters_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_companies_headquarters_location', 'companies', ['headquarters_location_id'], unique=False)
    op.create_index('idx_companies_name', 'companies', ['name'], unique=False)
    op.create_index('idx_companies_normalized_name', 'companies', ['normalized_name'], unique=False)
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_site_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('jobs_found', sa.Integer(), nullable=False),
    sa.Column('jobs_saved', sa.Integer(), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scrape_site_id'], ['scrape_sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scrape_runs_site', 'scrape_runs', ['scrape_site_id'], unique=False)
    op.create_index('idx_scrape_runs_started', 'scrape_runs', ['started_at'], unique=False)
    op.create_index('idx_scrape_runs_status', 'scrape_runs', ['status'], unique=False)
    op.create_table('skill_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('variant_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'variant_name')
    )
    op.create_index('idx_skill_variants_name', 'skill_variants', ['variant_name'], unique=False)
    op.create_index('idx_skill_variants_skill', 'skill_variants', ['skill_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('scrape_run_id', sa.Integer(), nullable=True),
    sa.Column('source_site_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('normalized_title', sa.String(length=255), nullable=True),
    sa.Column('years_min', sa.Integer(), nullable=True),
    sa.Column('years_max', sa.Integer(), nullable=True),
    sa.Column('years_overall', sa.Boolean(), nullable=False),
    sa.Column('salary_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('requires_german', sa.Boolean(), nullable=False),
    sa.Column('posted_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_site_id'], ['scrape_sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index('idx_jobs_company', 'jobs', ['company_id'], unique=False)
    op.create_index('idx_jobs_description_fts', 'jobs', [sa.literal_column("to_tsvector('english', description || ' ' || COALESCE(requirements, ''))")], unique=False, postgresql_using='gin')
    op.create_index('idx_jobs_external_id', 'jobs', ['external_id'], unique=False)
    op.create_index('idx_jobs_is_active', 'jobs', ['is_active'], unique=False)
    op.create_index('idx_jobs_job_type', 'jobs', ['job_type'], unique=False)
    op.create_index('idx_jobs_location', 'jobs', ['location_id'], unique=False)
    op.create_index('idx_jobs_posted', 'jobs', ['posted_date'], unique=False)
    op.create_index('idx_jobs_requires_german', 'jobs', ['requires_german'], unique=False)
    op.create_index('idx_jobs_scrape_run', 'jobs', ['scrape_run_id'], unique=False)
    op.create_index('idx_jobs_source_site', 'jobs', ['source_site_id'], unique=False)
    op.create_index('idx_jobs_source_url', 'jobs', ['source_url'], unique=False)
    op.create_index('idx_jobs_title', 'jobs', [sa.literal_column("to_tsvector('english', title)")], unique=False, postgresql_using='gin')
    op.create_index('idx_jobs_years', 'jobs', ['years_min', 'years_max'], unique=False)
    op.create_table('scrape_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=True),
    sa.Column('error_url', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('occurred_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scrape_errors_run', 'scrape_errors', ['scrape_run_id'], unique=False)
    op.create_index('idx_scrape_errors_type', 'scrape_errors', ['error_type'], unique=False)
    op.create_index('idx_scrape_errors_url', 'scrape_errors', ['error_url'], unique=False)
    op.create_table('job_categories_link',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['job_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'category_id')
    )
    op.create_table('job_languages',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('requirement_level', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'language')
    )
    op.create_index('idx_job_languages_job', 'job_languages', ['job_id'], unique=False)
    op.create_index('idx_job_languages_language', 'job_languages', ['language'], unique=False)
    op.create_index('idx_job_languages_language_level', 'job_languages', ['language', 'requirement_level'], unique=False)
    op.create_index('idx_job_languages_level', 'job_languages', ['requirement_level'], unique=False)
    op.create_table('job_skills',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'skill_id')
    )
    op.create_index('idx_job_skills_job', 'job_skills', ['job_id'], unique=False)
    op.create_index('idx_job_skills_skill', 'job_skills', ['skill_id'], unique=False)
    op.create_index('idx_job_skills_weight', 'job_skills', ['weight'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_job_skills_weight', table_name='job_skills')
    op.drop_index('idx_job_skills_skill', table_name='job_skills')
    op.drop_index('idx_job_skills_job', table_name='job_skills')
    op.drop_table('job_skills')
    op.drop_index('idx_job_languages_level', table_name='job_languages')
    op.drop_index('idx_job_languages_language_level', table_name='job_languages')
    op.drop_index('idx_job_languages_language', table_name='job_languages')
    op.drop_index('idx_job_languages_job', table_name='job_languages')
    op.drop_table('job_languages')
    op.drop_table('job_categories_link')
    op.drop_index('idx_scrape_errors_url', table_name='scrape_errors')
    op.drop_index('idx_scrape_errors_type', table_name='scrape_errors')
    op.drop_index('idx_scrape_errors_run', table_name='scrape_errors')
    op.drop_table('scrape_errors')
    op.drop_index('idx_jobs_years', table_name='jobs')
    op.drop_index('idx_jobs_title', table_name='jobs', postgresql_using='gin')
    op.drop_index('idx_jobs_source_url', table_name='jobs')
    op.drop_index('idx_jobs_source_site', table_name='jobs')
    op.drop_index('idx_jobs_scrape_run', table_name='jobs')
    op.drop_index('idx_jobs_requires_german', table_name='jobs')
    op.drop_index('idx_jobs_posted', table_name='jobs')
    op.drop_index('idx_jobs_location', table_name='jobs')
    op.drop_index('idx_jobs_job_type', table_name='jobs')
    op.drop_index('idx_jobs_is_active', table_name='jobs')
    op.drop_index('idx_jobs_external_id', table_name='jobs')
    op.drop_index('idx_jobs_description_fts', table_name='jobs', postgresql_using='gin')
    op.drop_index('idx_jobs_company', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('idx_skill_variants_skill', table_name='skill_variants')
    op.drop_index('idx_skill_variants_name', table_name='skill_variants')
    op.drop_table('skill_variants')
    op.drop_index('idx_scrape_runs_status', table_name='scrape_runs')
    op.drop_index('idx_scrape_runs_started', table_name='scrape_runs')
    op.drop_index('idx_scrape_runs_site', table_name='scrape_runs')
    op.drop_table('scrape_runs')
    op.drop_index('idx_companies_normalized_name', table_name='companies')
    op.drop_index('idx_companies_name', table_name='companies')
    op.drop_index('idx_companies_headquarters_location', table_name='companies')
    op.drop_table('companies')
    op.drop_index('idx_skills_category', table_name='skills')
    op.drop_index('idx_skills_canonical_name', table_name='skills')
    op.drop_table('skills')
    op.drop_table('scrape_sites')
    op.drop_index('idx_locations_remote', table_name='locations')
    op.drop_index('idx_locations_country', table_name='locations')
    op.drop_index('idx_locations_city', table_name='locations')
    op.drop_table('locations')
    op.drop_table('job_categories')
    # ### end Alembic commands ###
