"""add_search_criteria_and_hashing

Revision ID: 45a031e86221
Revises: 2fb47297112d
Create Date: 2026-05-12 18:40:29.631338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45a031e86221'
down_revision: Union[str, Sequence[str], None] = '2fb47297112d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_site_id', sa.Integer(), nullable=False),
    sa.Column('job_role', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('language_strict', sa.Boolean(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized_role', sa.String(length=255), nullable=True),
    sa.Column('normalized_location', sa.String(length=255), nullable=True),
    sa.Column('cohort_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scrape_site_id'], ['scrape_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cohort_hash')
    )
    op.create_index('idx_search_criteria_cohort', 'search_criteria', ['cohort_hash'], unique=False)
    op.create_index('idx_search_criteria_site_role_loc', 'search_criteria', ['scrape_site_id', 'job_role', 'location'], unique=False)
    op.drop_index(op.f('idx_companies_name'), table_name='companies')
    op.create_index('idx_companies_name_btree', 'companies', ['name'], unique=False)
    op.create_index('idx_companies_name_fts', 'companies', [sa.literal_column("to_tsvector('english', name)")], unique=False, postgresql_using='gin')
    op.add_column('jobs', sa.Column('search_criteria_id', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('last_seen_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('idx_jobs_description_fts'), table_name='jobs', postgresql_using='gin')
    op.create_index('idx_jobs_description_fts', 'jobs', [sa.literal_column("to_tsvector('english', description || ' ' || COALESCE(requirements, ''))")], unique=False, postgresql_using='gin')
    op.create_index('idx_jobs_criteria', 'jobs', ['search_criteria_id'], unique=False)
    op.create_index('idx_jobs_last_seen', 'jobs', ['last_seen_at'], unique=False)
    op.create_foreign_key(None, 'jobs', 'search_criteria', ['search_criteria_id'], ['id'], ondelete='SET NULL')
    op.add_column('scrape_runs', sa.Column('search_criteria_id', sa.Integer(), nullable=True))
    op.create_index('idx_scrape_runs_criteria', 'scrape_runs', ['search_criteria_id'], unique=False)
    op.create_foreign_key(None, 'scrape_runs', 'search_criteria', ['search_criteria_id'], ['id'], ondelete='SET NULL')
    op.drop_column('scrape_runs', 'search_criteria')
    op.drop_index(op.f('idx_skills_canonical_name'), table_name='skills')
    op.create_index('idx_skills_canonical_name_btree', 'skills', ['canonical_name'], unique=False)
    op.create_index('idx_skills_name_fts', 'skills', [sa.literal_column("to_tsvector('english', canonical_name)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_skills_name_fts', table_name='skills', postgresql_using='gin')
    op.drop_index('idx_skills_canonical_name_btree', table_name='skills')
    op.create_index(op.f('idx_skills_canonical_name'), 'skills', ['canonical_name'], unique=False)
    op.add_column('scrape_runs', sa.Column('search_criteria', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'scrape_runs', type_='foreignkey')
    op.drop_index('idx_scrape_runs_criteria', table_name='scrape_runs')
    op.drop_column('scrape_runs', 'search_criteria_id')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index('idx_jobs_last_seen', table_name='jobs')
    op.drop_index('idx_jobs_criteria', table_name='jobs')
    op.drop_index('idx_jobs_description_fts', table_name='jobs', postgresql_using='gin')
    op.create_index(op.f('idx_jobs_description_fts'), 'jobs', [sa.literal_column("to_tsvector('english'::regconfig, (description || ' '::text) || COALESCE(requirements, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_column('jobs', 'last_seen_at')
    op.drop_column('jobs', 'search_criteria_id')
    op.drop_index('idx_companies_name_fts', table_name='companies', postgresql_using='gin')
    op.drop_index('idx_companies_name_btree', table_name='companies')
    op.create_index(op.f('idx_companies_name'), 'companies', ['name'], unique=False)
    op.drop_index('idx_search_criteria_site_role_loc', table_name='search_criteria')
    op.drop_index('idx_search_criteria_cohort', table_name='search_criteria')
    op.drop_table('search_criteria')
    # ### end Alembic commands ###
